### PR TITLE
Add BigInt support

### PR DESCRIPTION
**Pull request by prodrigestivill**
As a proposal it would be helpfull to have calls to handle bigint in case of handling Big Integer Ids from a DB.

I implemented initially using npm [big-integer](https://github.com/peterolson/BigInteger.js) library.

I also implemented as a complementary library on my repository [hashids-bigint](https://github.com/prodrigestivill/hashids-bigint).

This library is not yet published to npm, because I believe it would be better to have support in the same library.

Let me know what do you think, I undestand that adding an optional dependency might not be desirable.

Possible solutions:
- It can be implemented to support javascript [native bigint](https://tc39.github.io/proposal-bigint/) but this might be too new.
- It can be implemented as required dependency.

### CODE REVIEW

**Comment by prodrigestivill** [comment]
Travis checks fails for the node / babel version, unrelated with the pull-request.
It works for me changing `maintained node versions` to `node 10` in the `package.json` from this [comment](https://github.com/browserslist/browserslist/issues/311#issuecomment-432143280).

But not sure if this makes sense to fix from this pull-request.

So it is only needed to update babel versions: [browserslist#311](https://github.com/browserslist/browserslist/issues/311).

**Comment by j-f1** [comment]
Does this work with native `BigInt`s?

**Comment by prodrigestivill** [comment]
Tested with native `BigInt`s and working. But still relaying to the external library in order to perform hex conversion.

**Comment by r3dh4r7** [comment]
`BigInt` uses strings. I personally use `BigNumber` which also uses strings.
According to [hashids.org](hashids.org):

> **Do not encode strings.** We've had several requests to add this feature — "it seems so easy to add". We will not add this feature for security purposes, doing so encourages people to encode sensitive data, like passwords. This is the wrong tool for that.

Kindly publish your repo to NPM. I don't think this PR will ever be merged.

**Comment by r3dh4r7** [comment]
Seeing as its over a month now, you should publish this to NPM. Override the `encode` and `decode` functions so one can easily swap from `hashids` to `hashids-bigint` without refactoring.

You can always deprecate the `hashids-bigint` package if the original `hashids` package decides to support arbitrary string numbers like `BigInt` & `BigNumber`.

**Comment by prodrigestivill** [comment]
> Override the `encode` and `decode` functions so one can easily swap from `hashids` to `hashids-bigint` without refactoring.

It seams a good idea, but it will need more work, currently I was using the BigInt to Hex and encodeHex function, but aparently the @ivanakimov implementation of `encodeHex` in hashids is not compatible with `encode` for regular numbers, so currently my patch and fork does the following:

```
encodeBI(1n) = encodeHex('01')
encodeHex('01') != encode(1)
encodeBI(1n) != encode(1)
```
I didn't expect this behavior, I will try to take a look and do at least `encodeBI` compatible with `encode` if the plan is to do a library backcompatible with the same calls.

So, it might take change all `hashids` calls to use BigInt modulus at least.
In this case it will end as a full refactor of the library. I will code it when I have time.

**Comment by r3dh4r7** [comment]
I've deviced a workaround with hex using `bignumber.js` and the original `hashids.js`.

Encode:
```hashids.encodeHex(new BigNumber(NUMBER_STRING).toString(16))```

Decode:
```new BigNumber(`0x${hashids.decodeHex(HASHED_STRING)}`).toString()```

**Comment by ivanakimov** [comment]
Thanks for experimenting with this, everyone.

There have been some requests in the past for supporting bigger numbers, but I haven't noticed many lately. It's true, we've tried to avoid depending on other modules to keep the codebase small and less complex, so the advice has usually been to split up the numbers yourself (if they're too big) before encoding. But I agree that having built-in support would of course be ideal.

If there's a way to use JavaScript's `BigInt` internally wherever it's available, I'd support this implementation. As far as I'm aware, some other Hashids implementations use a similar approach. I'd be cautious about relying on external dependencies, but am open to discussion if there's demand for it.

Otherwise, feel free to fork or build on top of Hashids, and I'll link to your repo on the website.

**Comment by Bessonov** [comment]
@ivanakimov interested in it for node, which supports `BigInt` after v10.4.0. But becase some browsers doesn't support it, may be you can offer an api to hook into and provide a custom polyfill or native implementation. Then you don't have any dependency on `BigInt` nor a specific implementation.

**Comment by niieani** [comment]
@Bessonov I'll look into it. I'm curious - what's your use case?

**Comment by Bessonov** [comment]
I want to switch to CockroachDB, which offers some compatibility with Postgresql and stores primary key as 64-bit integer. Currently, `pg` driver returns it as a string, but it can be converted to `BigInt`.

**Comment by niieani** [comment]
Thanks a lot @prodrigestivill for your proposal. I have decided it would be best if the BigInt support were transparent (rather than using a custom function for it). 

A beta version with BigInt support (using standard APIs) is released as `hashids@next` (PR #65). See the updated README for details.

Looking forward to your feedback!

**Pull request closed without merging**
