### PR TITLE
Adds .npmignore

### PR DESCRIPTION
**Pull request by ryanblock**
Took the approach that dist belongs in source but not in package manager (~if it's not being used, which in this case it is not~*), but you may have diff feels on that.

If so, can just edit**  or remove L8. As is:

### Before
```
npm notice === Tarball Details ===
npm notice name:          hashids
npm notice version:       1.2.2
npm notice package size:  19.1 kB
npm notice unpacked size: 94.8 kB
npm notice shasum:        8c2b36a4559430c90e466b3b7519f3c2862909d6
npm notice integrity:     sha512-jp+XlsrjkdcEm[...]drOEUTA5qUTsQ==
npm notice total files:   13
```

### After
```
npm notice === Tarball Details ===
npm notice name:          hashids
npm notice version:       1.2.2
npm notice package size:  7.5 kB
npm notice unpacked size: 20.6 kB
npm notice shasum:        9160e6576f8f8121bb9f9f82d3435b99ee21717a
npm notice integrity:     sha512-65lWfP6p8Yopr[...]rOFokk++h2Dww==
npm notice total files:   5
```

*Update: that was wrong, it is! (Just not by my use case.)
**Suggest at least consider npmignoring `.map`s

### CODE REVIEW

**Comment by ryanblock** [comment]
Just a heads up, this change would require some minor reconfiguration of Travis; tests should be run against the git repo (where the tests are), not the npm package, so build steps should be updated to git clone this repo (instead of installing the published npm artifact).

**Comment by ivanakimov** [comment]
@ryanblock Is it something you'd have to adjust in `.travis.yml`?

**Comment by ryanblock** [comment]
Apologies, I misread something in the code – turns out deps were just stale and needed to be updated. Should be cleared for takeoff!

**Comment by ivanakimov** [comment]
Cool, thanks. What if devs install with npm and link directly to `dist/hashids.min.js` on frontend or backend - would that not work anymore?

**Comment by ryanblock** [comment]
Will respond further asap, but please don't merge yet! Sorry for the rollercoaster here.

**Comment by ryanblock** [comment]
Sorry, took me a few days to get back to this! Thanks for not merging immediately, I did not look closely enough at how this was configured and not including `dist/` in the npm package would probably have broken things for someone. 😅

npmignore now only excludes non `dist/` and `lib/` files, so it should be good to merge. It's a marginal improvement (but an improvement all the same!), and brings us back to the original question of the intention of `dist/`. 

There are a lot of build artifacts being transpiled for distribution across a variety of use cases, and perhaps not all are necessary. (Whether that's definitely the case I do not know, more on that in a second.) That said, I'd like to think that for those kinds of artifacts (and for conveniences like source maps) folks could acquire them periodically from the git repo instead of via npm.

But I'm also willing to accept that perhaps that's an over-optimization that sacrifices this project's versatility (and conclude that perhaps I should just maintain a fork).

Perhaps you can lend some knowledge of the feedback you've received on your project with regards to how people use it (browser vs server side, etc.) that could guide that kind of decision?

Either way, we've made a bit of an improvement in npm hygiene here, so yay! 🌈

**Comment by ivanakimov** [comment]
Thanks @ryanblock. Don't have that much feedback into how/where people use it, but any improvement is appreciated.

Did a bit more reading on `.npmignore`, like [this](https://medium.com/@jdxcode/for-the-love-of-god-dont-use-npmignore-f93c08909d8d) and [this](https://blog.npmjs.org/post/165769683050/publishing-what-you-mean-to-publish). Any benefits to using `files` in `package.json` over this?

**Comment by ryanblock** [comment]
Either is fine! I prefer `.npmignore` in this case because the project is stable and not undergoing much change (which is a Good Thing), so we don't have to be too concerned about ensuring newly created files don't leak into the project.

I get the argument in favor of `files` over `.npmignore`, but I think in a project like that's stabilized, the safety of specifying the files to include (as opposed to specifying the files to exclude) isn't of much benefit.

It also means that if your build artifacts change at all in the future, you have to remember to add them to `files`. That blog post is a bit outdated and a little overdramatic IMO, but both approaches work!

**Comment by ryanblock** [comment]
👋🏻

**Pull request closed without merging**
